require 'simplecov'
SimpleCov.start do
  add_filter("/test")
end
require 'minitest/pride'
require 'minitest/autorun'
require './lib/sales_engine'
require './lib/file_io'
require './lib/customer_repository'
require './lib/customer'
require './lib/invoice_item_repository'
require './lib/invoice_item'
require './lib/invoice_repository'
require './lib/invoice'
require './lib/item_repository'
require './lib/item'
require './lib/merchant_repository'
require './lib/merchant'
require './lib/transaction_repository'
require './lib/transaction'
